{{- if .Values.rbac.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "teamcity.fullname" . }}:manage-agents
  namespace: {{ template "teamcity.namespace" . }}
  labels:
    {{- include "teamcity.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "teamcity.fullname" . }}:manage-agents
subjects:
  - kind: ServiceAccount
    name: {{ template "teamcity.fullname" . }}
{{- end }}
